"""Compare two reports and write the issue body as markdown.

Usage: python scripts/compare.py PREVIOUS.json CURRENT.json OUTPUT.md

Prints `changed=true|false` on stdout in the format GITHUB_OUTPUT expects.
The markdown goes to a file rather than a multiline output because
`gh issue create --body-file` needs no escaping at all.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from domainwalk.diff import diff_reports

ARROW = {"worse": "down", "better": "up"}


def render(delta: dict) -> str:
    lines: list[str] = []
    lines.append(f"Comparison of **{delta['domain']}** between `{delta['from']}` and `{delta['to']}`.")
    lines.append("")

    grade = delta["grade"]
    if grade["changed"]:
        lines.append(f"Grade moved from **{grade['from']}** to **{grade['to']}**.")
        lines.append("")

    changed = delta["findings"]["changed"]
    if changed:
        lines.append("### Severity changes")
        lines.append("")
        lines.append("| | id | before | now | detail |")
        lines.append("|---|---|---|---|---|")
        for item in changed:
            lines.append(
                f"| {ARROW[item['direction']]} | `{item['id']}` | {item['from']} | "
                f"**{item['to']}** | {item['msg']} |"
            )
        lines.append("")
        fixes = [i for i in changed if i["direction"] == "worse" and i.get("fix")]
        if fixes:
            lines.append("**How to fix**")
            lines.append("")
            for item in fixes:
                lines.append(f"- `{item['id']}` - {item['fix']}")
            lines.append("")

    for key, title in (("new", "New findings"), ("resolved", "Findings that are gone")):
        items = delta["findings"][key]
        if not items:
            continue
        lines.append(f"### {title}")
        lines.append("")
        for item in items:
            lines.append(f"- `{item['id']}` ({item['level']}) - {item['msg']}")
        lines.append("")

    if delta["records"]:
        lines.append("### DNS records")
        lines.append("")
        for field, change in delta["records"].items():
            for value in change["added"]:
                lines.append(f"- **+** `{field}` - {value}")
            for value in change["removed"]:
                lines.append(f"- **-** `{field}` - {value}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Generated by the weekly check. Opening this issue also updates the "
        "baseline, so the next comparison starts from this state and the alert "
        "will not repeat."
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    old_path, new_path, body_path = argv[1], argv[2], argv[3]

    new = json.loads(Path(new_path).read_text(encoding="utf-8"))
    if not Path(old_path).is_file():
        # First run, nothing to compare against, so the current state becomes the baseline.
        print("changed=false")
        print("first_run=true")
        return 0

    old = json.loads(Path(old_path).read_text(encoding="utf-8"))
    delta = diff_reports(old, new)
    Path(body_path).write_text(render(delta), encoding="utf-8")
    print(f"changed={'false' if delta['unchanged'] else 'true'}")
    print("first_run=false")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
